### ISSUE TITLE
How to load Night-time Driving set

### ISSUE THREAD

**Issue by jdg900** [W-zx-Y/DANNet#13]
Thank you for sharing the code of your excellent work.

I have a question about your implementation.

When you evaluate your work on Night-time Driving set, did you load the dataset using cityscapes_dataset.py?

I'm looking forward to hearing from you!

Thanks!

**Comment by W-zx-Y** [comment]
Hi @jdg900, 
During the evaluation, we loaded the Night-Driving dataset by using "zurich_night_dataset.py". The prerequisite is creating a list for all testing images.

**Comment by jdg900** [comment]
Thank you!
