### ISSUE TITLE
About DANIA

### ISSUE THREAD

**Issue by jimmy9704** [W-zx-Y/DANNet#14]
I am very much inspired by your follow-up paper, DANIA. 
I would like to test DANIA on different data sets.
Can you share the model weights of DANIA?

**Comment by W-zx-Y** [comment]
I appreciate your interest in our work. Below is the dropbox link to download the DANIA-PSP checkpoints. It can be run with the DANNet repo.
https://www.dropbox.com/sh/irz36lc05o1k2d4/AACFyrUA-hH0z7caPiSK_L40a?dl=0    

The checkpoints and results (DAINIA-DeepLab) on the ACDC dataset are in the following dropbox link.
https://www.dropbox.com/sh/16x1zvzuf29sy51/AAAr58UEiaCzJwP1qPw0qnLfa?dl=0

The PSPNet-based DANIA checkpoints on the acdc-all setting can be found at this link: https://www.dropbox.com/sh/i9kfxktxqgg4y7e/AAA0lJvTpuViPLL53q5cwX7Va?dl=0

**Comment by jimmy9704** [comment]
thank you!!
