### ISSUE TITLE
How to reproduce the reported results on Dark-Zurich-test

### ISSUE THREAD

**Issue by JCongLang** [W-zx-Y/DANNet#17]
I would like to reproduce the reported results on Dark-Zurich-test
Can you share the code of testing ?

**Comment by cixiao2022** [comment]
Hi，Have you solved your issue? I have the same problem.

**Comment by JCongLang** [comment]
> Hi，Have you solved your issue? I have the same problem.

Submit your results to https://codalab.lisn.upsaclay.fr/competitions/3783#participate
and you will get miou on Dark-Zurich-test

**Comment by cixiao2022** [comment]
Thank you!!

**Comment by Urbenyy** [comment]
> > Hi，Have you solved your issue? I have the same problem.
> 
> Submit your results to https://codalab.lisn.upsaclay.fr/competitions/3783#participate and you will get miou on Dark-Zurich-test

Hello, I would like to bother you. Have you solved this problem? I have been uploading problematic results recently. I still have errors when uploading according to the steps written by the author. Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png
=======UIoU=ERROR =======
Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png
======= Avg_UIoU=ERROR =======
Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png
======= IoU=ERROR =======
May I ask how you solved it?

**Comment by JCongLang** [comment]
> > > Hi，Have you solved your issue? I have the same problem.
> > 
> > 
> > Submit your results to https://codalab.lisn.upsaclay.fr/competitions/3783#participate and you will get miou on Dark-Zurich-test
> 
> Hello, I would like to bother you. Have you solved this problem? I have been uploading problematic results recently. I still have errors when uploading according to the steps written by the author. Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png =======UIoU=ERROR ======= Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png ======= Avg_UIoU=ERROR ======= Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png ======= IoU=ERROR ======= May I ask how you solved it?

Is the prediction you uploaded like this?
![image](https://github.com/W-zx-Y/DANNet/assets/108472371/31f6bda7-03e6-437f-a7d4-b9c49e97a1e1)

or colorful？

**Comment by Urbenyy** [comment]
colorful

> > > > Hi，Have you solved your issue? I have the same problem.
> > > 
> > > 
> > > Submit your results to https://codalab.lisn.upsaclay.fr/competitions/3783#participate and you will get miou on Dark-Zurich-test
> > 
> > 
> > Hello, I would like to bother you. Have you solved this problem? I have been uploading problematic results recently. I still have errors when uploading according to the steps written by the author. Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png =======UIoU=ERROR ======= Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png ======= Avg_UIoU=ERROR ======= Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png ======= IoU=ERROR ======= May I ask how you solved it?
> 
> Is the prediction you uploaded like this? ![image](https://private-user-images.githubusercontent.com/108472371/316850184-31f6bda7-03e6-437f-a7d4-b9c49e97a1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ1OTQsIm5iZiI6MTcxMTQ1NDI5NCwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODUwMTg0LTMxZjZiZGE3LTAzZTYtNDM3Zi1hN2Q0LWI5YzQ5ZTk3YTFlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMTU4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGNhNjI2ZWRjNjMxOGIwMmJiYjFiMjE4YzllODI2ZmJhZTVhN2JjNmI3YjBjNWVhNjcwZWNhN2Q3MTk4ZTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CTwB7XNKf5cyt-hPGmGeJmMxPwfbasCCT2GE5i9CDww)
> 
> or colorful？

colorful
![Uploading 2.png…]()

**Comment by Urbenyy** [comment]
![1](https://github.com/W-zx-Y/DANNet/assets/96567010/e3f7f250-2d91-41ba-83e5-c337f02d29ac)
![2](https://github.com/W-zx-Y/DANNet/assets/96567010/a5e1d30f-160e-4698-8acd-8937c5505d9c)
colorful,Should I upload like you do?I'll try it

**Comment by JCongLang** [comment]
> ![1](https://private-user-images.githubusercontent.com/96567010/316852223-e3f7f250-2d91-41ba-83e5-c337f02d29ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ5NjEsIm5iZiI6MTcxMTQ1NDY2MSwicGF0aCI6Ii85NjU2NzAxMC8zMTY4NTIyMjMtZTNmN2YyNTAtMmQ5MS00MWJhLTgzZTUtYzMzN2YwMmQyOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmZjMmQ3ZmJjNjc1MWRmNmQ3YzkwOGYzYmRkYzBkMGZlZjk1YjNlNjI1Y2ZhYThjMWNjZmQxOGNiZGRlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wsxh4DHpq3LTDRrRWW6jrQsigxORIn110TAFchYKbg) ![2](https://private-user-images.githubusercontent.com/96567010/316852258-a5e1d30f-160e-4698-8acd-8937c5505d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ5NjEsIm5iZiI6MTcxMTQ1NDY2MSwicGF0aCI6Ii85NjU2NzAxMC8zMTY4NTIyNTgtYTVlMWQzMGYtMTYwZS00Njk4LThhY2QtODkzN2M1NTA1ZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZjRhMWQ3ZjM1ZDc1Y2I5ZmUzZGI5NDE4MDRlMWZhMjdmNjViMWY1NmE4YjIwNWRkMjFmOTAwYTVkYjdjMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RvPehbwU-T8p15wFjJUA2GKtHJbRzFx8YOkdPPy_sA) colorful,Should I upload like you do?I'll try it

yes

**Comment by Urbenyy** [comment]
> > ![1](https://private-user-images.githubusercontent.com/96567010/316852223-e3f7f250-2d91-41ba-83e5-c337f02d29ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ5NjEsIm5iZiI6MTcxMTQ1NDY2MSwicGF0aCI6Ii85NjU2NzAxMC8zMTY4NTIyMjMtZTNmN2YyNTAtMmQ5MS00MWJhLTgzZTUtYzMzN2YwMmQyOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmZjMmQ3ZmJjNjc1MWRmNmQ3YzkwOGYzYmRkYzBkMGZlZjk1YjNlNjI1Y2ZhYThjMWNjZmQxOGNiZGRlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wsxh4DHpq3LTDRrRWW6jrQsigxORIn110TAFchYKbg) ![2](https://private-user-images.githubusercontent.com/96567010/316852258-a5e1d30f-160e-4698-8acd-8937c5505d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTQ5NjEsIm5iZiI6MTcxMTQ1NDY2MSwicGF0aCI6Ii85NjU2NzAxMC8zMTY4NTIyNTgtYTVlMWQzMGYtMTYwZS00Njk4LThhY2QtODkzN2M1NTA1ZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZjRhMWQ3ZjM1ZDc1Y2I5ZmUzZGI5NDE4MDRlMWZhMjdmNjViMWY1NmE4YjIwNWRkMjFmOTAwYTVkYjdjMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RvPehbwU-T8p15wFjJUA2GKtHJbRzFx8YOkdPPy_sA) colorful,Should I upload like you do?I'll try it
> 
> yes

I just uploaded it, but the result is still wrong

**Comment by Urbenyy** [comment]
I'm so sorry to trouble you, let me show you my file structure
![image](https://github.com/W-zx-Y/DANNet/assets/96567010/1e8630c3-d032-4f9f-bdfb-399098b7c066)
![image](https://github.com/W-zx-Y/DANNet/assets/96567010/3efff818-ce8d-4378-9ff5-19d83e954fde)
![image](https://github.com/W-zx-Y/DANNet/assets/96567010/39eff325-5145-4b2a-872f-98878b505610)
![image](https://github.com/W-zx-Y/DANNet/assets/96567010/f9cf9983-776c-460f-93eb-27bf8a408ad9)

**Comment by JCongLang** [comment]
Try uploading a compressed file containing only the 'labelTrainIds' folder. 
my file structure is like this：
![image](https://github.com/W-zx-Y/DANNet/assets/108472371/5d9f091c-cb03-4e25-a064-d93151d9af0c)
![image](https://github.com/W-zx-Y/DANNet/assets/108472371/a319287b-5775-4ebb-a783-8e9e8d6a2ae5)

If this doesn't work, I don't know what's wrong.

**Comment by Urbenyy** [comment]
> 尝试上传仅包含“labelTrainIds”文件夹的压缩文件。 我的文件结构是这样的： ![图像](https://private-user-images.githubusercontent.com/108472371/316861760-5d9f091c-cb03-4e25-a064-d93151d9af0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxNzYwLTVkOWYwOTFjLWNiMDMtNGUyNS1hMDY0LWQ5MzE1MWQ5YWYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGVlMjNmNDc1MGUyMGJkZjRjYmJkMDA3YjQ1MzA4YmI0YWM5ZDk3ZTRjZmU4ZDQ5ZjVjYjIzZWZhMGJkMDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bh9JK3X3sigXl9iJlL1LpOGJ31J76ywzi0ybAshbYN4) ![图像](https://private-user-images.githubusercontent.com/108472371/316861895-a319287b-5775-4ebb-a783-8e9e8d6a2ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxODk1LWEzMTkyODdiLTU3NzUtNGViYi1hNzgzLThlOWU4ZDZhMmFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZiM2RhNzI5MzEzZjUwNzNhMGM2ZDQ2MGNkMDY5ZWFlOGYwYTNjYTQzZTI5YjA5Y2VmZmQyYmFjZWE2ZGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zMX5rvwKxfOZNG3yhwwdmCu7Mf2c227LtNG3GwDsIfU)
> 
> 如果这不起作用，我不知道出了什么问题。

好的谢谢你我去试一下哈哈哈哈你也是中国人我就不用英文了，谢谢你的耐心解答！！

**Comment by JCongLang** [comment]
> > 尝试上传仅包含“labelTrainIds”文件夹的压缩文件。 我的文件结构是这样的： ![图像](https://private-user-images.githubusercontent.com/108472371/316861760-5d9f091c-cb03-4e25-a064-d93151d9af0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxNzYwLTVkOWYwOTFjLWNiMDMtNGUyNS1hMDY0LWQ5MzE1MWQ5YWYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGVlMjNmNDc1MGUyMGJkZjRjYmJkMDA3YjQ1MzA4YmI0YWM5ZDk3ZTRjZmU4ZDQ5ZjVjYjIzZWZhMGJkMDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bh9JK3X3sigXl9iJlL1LpOGJ31J76ywzi0ybAshbYN4) ![图像](https://private-user-images.githubusercontent.com/108472371/316861895-a319287b-5775-4ebb-a783-8e9e8d6a2ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxODk1LWEzMTkyODdiLTU3NzUtNGViYi1hNzgzLThlOWU4ZDZhMmFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZiM2RhNzI5MzEzZjUwNzNhMGM2ZDQ2MGNkMDY5ZWFlOGYwYTNjYTQzZTI5YjA5Y2VmZmQyYmFjZWE2ZGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zMX5rvwKxfOZNG3yhwwdmCu7Mf2c227LtNG3GwDsIfU)
> > 如果这不起作用，我不知道出了什么问题。
> 
> 好的谢谢你我去试一下哈哈哈哈你也是中国人我就不用英文了，谢谢你的耐心解答！！

不用谢，哈哈

**Comment by Urbenyy** [comment]
> > > 尝试上传仅包含“labelTrainIds”文件夹的压缩文件。 我的文件结构是这样的： ![图像](https://private-user-images.githubusercontent.com/108472371/316861760-5d9f091c-cb03-4e25-a064-d93151d9af0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxNzYwLTVkOWYwOTFjLWNiMDMtNGUyNS1hMDY0LWQ5MzE1MWQ5YWYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGVlMjNmNDc1MGUyMGJkZjRjYmJkMDA3YjQ1MzA4YmI0YWM5ZDk3ZTRjZmU4ZDQ5ZjVjYjIzZWZhMGJkMDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bh9JK3X3sigXl9iJlL1LpOGJ31J76ywzi0ybAshbYN4) ![图像](https://private-user-images.githubusercontent.com/108472371/316861895-a319287b-5775-4ebb-a783-8e9e8d6a2ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxODk1LWEzMTkyODdiLTU3NzUtNGViYi1hNzgzLThlOWU4ZDZhMmFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZiM2RhNzI5MzEzZjUwNzNhMGM2ZDQ2MGNkMDY5ZWFlOGYwYTNjYTQzZTI5YjA5Y2VmZmQyYmFjZWE2ZGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zMX5rvwKxfOZNG3yhwwdmCu7Mf2c227LtNG3GwDsIfU)
> > > 如果这不起作用，我不知道出了什么问题。
> > 
> > 
> > 好的谢谢你我去试一下哈哈哈哈你也是中国人我就不用英文了，谢谢你的耐心解答！！
> 
> 不用谢，哈哈

谢谢你！！成功了！！！！

**Comment by JCongLang** [comment]
> > > > 尝试上传仅包含“labelTrainIds”文件夹的压缩文件。 我的文件结构是这样的： ![图像](https://private-user-images.githubusercontent.com/108472371/316861760-5d9f091c-cb03-4e25-a064-d93151d9af0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxNzYwLTVkOWYwOTFjLWNiMDMtNGUyNS1hMDY0LWQ5MzE1MWQ5YWYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGVlMjNmNDc1MGUyMGJkZjRjYmJkMDA3YjQ1MzA4YmI0YWM5ZDk3ZTRjZmU4ZDQ5ZjVjYjIzZWZhMGJkMDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bh9JK3X3sigXl9iJlL1LpOGJ31J76ywzi0ybAshbYN4) ![图像](https://private-user-images.githubusercontent.com/108472371/316861895-a319287b-5775-4ebb-a783-8e9e8d6a2ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY5MTUsIm5iZiI6MTcxMTQ1NjYxNSwicGF0aCI6Ii8xMDg0NzIzNzEvMzE2ODYxODk1LWEzMTkyODdiLTU3NzUtNGViYi1hNzgzLThlOWU4ZDZhMmFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZiM2RhNzI5MzEzZjUwNzNhMGM2ZDQ2MGNkMDY5ZWFlOGYwYTNjYTQzZTI5YjA5Y2VmZmQyYmFjZWE2ZGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zMX5rvwKxfOZNG3yhwwdmCu7Mf2c227LtNG3GwDsIfU)
> > > > 如果这不起作用，我不知道出了什么问题。
> > > 
> > > 
> > > 好的谢谢你我去试一下哈哈哈哈你也是中国人我就不用英文了，谢谢你的耐心解答！！
> > 
> > 
> > 不用谢，哈哈
> 
> 谢谢你！！成功了！！！！

：）
