### ISSUE TITLE
Model weight selection

### ISSUE THREAD

**Issue by creater-zq** [W-zx-Y/DANNet#6]
Hello!  Your paper has inspired me a lot. Thank you.  
Meanwhile, I used the code you provided for training to reproduce the results. I trained 50,000 times according to the code and got a weight file for every 1,000 times. May I ask whether the final weight used for validation and testing was obtained in the last round (i.e. 50,000 round)?  
Have you used trained intermediate weights for validation and testing, such as the .pth file from 40,000 rounds of training?

**Comment by W-zx-Y** [comment]
Thanks. 
We train all model variants for 35,000 iteration, which means we use the dannet35000.pth for validation and testing.

**Comment by mradul2** [comment]
> Hello! Your paper has inspired me a lot. Thank you. Meanwhile, I used the code you provided for training to reproduce the results. I trained 50,000 times according to the code and got a weight file for every 1,000 times. May I ask whether the final weight used for validation and testing was obtained in the last round (i.e., 50,000 rounds)? Have you used trained intermediate weights for validation and testing, such as the .pth file from 40,000 rounds of training?

Hey @creater-zq, could you please tell, what computational device you were using (Number and type of GPU/TPU's) and approximately how much time it was required for these 50,000 epochs for the three models you would have trained. Looking forward to hearing from you.

**Comment by Brokkoi** [comment]
When I choose 35000.pth, the performance is much lower than with 50000.pth. Why is that?
