### ISSUE TITLE
enhancement = enhancement*mean_std[1]+mean_std[0] 

### ISSUE THREAD

**Issue by creater-zq** [W-zx-Y/DANNet#7]
Hello! I encountered an error while running evaluate.py
* NameError: name 'mean_std' is not defined
* 
I tried to find the definition of the variable mean_std but could not find it, could you please tell me how to fix this error? thanks

**Comment by ZhenyaoWu** [comment]
To save the enhanced image, you can use the following code to set the mean value and the std value.
`mean_std = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`

**Comment by W-zx-Y** [comment]
To save the enhanced image, you can use the following code to set the mean value and the std value.
`mean_std = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`
